/*
 *
 * ultrasonic.h
 *
 *  Created on: Oct 17, 2021
 *      Author: lenovo
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_
#include "GPIO.h"
#include "timer.h"
#define ECHO_PORT ICU_PORT
#define ECHO_PIN ICU_PIN
typedef enum
{
	ULTRASONIC1,
	ULTRASONIC2,
	ULTRASONIC3,
	ULTRASONIC4

}enULTRASONICE_NUMBER;
typedef enum
{
	ULTRASONIC1_TRIGGER_PORT =GPIO_D,
	ULTRASONIC2_TRIGGER_PORT =GPIO_D,
	ULTRASONIC3_TRIGGER_PORT =GPIO_D,
	ULTRASONIC4_TRIGGER_PORT =GPIO_D

}enULTRASONIC_TRUGGER_PORT;
typedef enum
{
	ULTRASONIC1_TRIGGER_PIN =GPIO_PIN0,
	ULTRASONIC2_TRIGGER_PIN =GPIO_PIN1,
	ULTRASONIC3_TRIGGER_PIN =GPIO_PIN2,
	ULTRASONIC4_TRIGGER_PIN =GPIO_PIN3

}enULTRASONIC_TRUGGER_PIN;
static void FUNC_OVF() ;
static void FUNC_ICU() ;
void static ULTRASONIC_START(enULTRASONICE_NUMBER ultrasonic_number);


#endif /* ULTRASONIC_H_ */
